### ISSUE TITLE
Variáveis de cor no CSS

### ISSUE THREAD

**Issue by dev-ggomes** [victorgs062/meu-primeiro-site#1]
## Não use os códigos hexadecimais das cores

Você pode usar variáveis de cor para uma melhor prática de código, em sites maiores ou que apresentam algum tipo de serviço fica melhor usar variáveis de cor no CSS para ser mais fácil de alterar caso seja preciso. Vou lhe dar um exemplo de como usar variáveis de cor no CSS: ⏬ 

```CSS
:root {
    --color-white: #fff;
}

body {
    background-color: var(--color-white);
}
``` 
> Com cores neutras como **preto**, **branco** ou **tons de cinzento** você consegue colocar simplesmente os 3 primeiros caracteres do hexadecimal da cor na variável. No exemplo que mostrei a cor é `branco` (hexadecimal de branco é `#ffffff`) então se colocar apenas `#fff` ele já assume como branco.
---
Irei colocar os seus códigos CSS `estilo_index.css` e `estilo_sobre.css` aqui adaptados com as variáveis de cor. Sinta-se livre para tirar qualquer dúvida que tenha sobre variáveis de cor ou sobre CSS, o que eu conseguir ajudar eu ajudarei 🚀  

### `estilo_index.css`
```CSS
:root {
    --color-light-green: #64AC72; /* Verde claro */
    --color-light-gray: #BCBCBC; /* Cinza claro */
    --color-light-gray2: #A4A4A4; /* Outro cinza claro */
    --color-gray: #9B9FA5; /* Cinza */
    --color-dark-gray: #333; /*  Cinza escuro */
    --color-dark-gray2: #2E2E2E /* Outro cinza escuro */
    --color-white: #f9f9f9; /* Cor quase branco */
    --color-white2: #E0E0E0; /* Outro quase branco */
}

* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

body {
    font-family: Arial, Helvetica, sans-serif;
    background: url('images/background.png') no-repeat center center / cover;
    background-attachment: fixed;
    min-height: 100vh;
    font-size: 24px;
    color: var(--color-dark-gray);
    background-color: var(--color-white);
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    line-height: 1.6;
    margin: 20px;
}

.container {
    padding: 36px;
    color: var(--color-gray);
    position: absolute;
    top: 250px;
    left: 20px;
    width: 600px;
    height: auto;
}

h1 {
    font-size: 24px;
    margin-bottom: 10px;
    color: var(--color-white2); 
    font-weight: 300;
}

.description {
    font-size: 24px;
    margin-bottom: 20px;
    color: var(--color-light-gray); 
}

h2 {
    font-size: 24px;
    margin-bottom: 10px;
    color: var(--color-white2); 
    font-weight: 300; 
}

.team {
    list-style-type: none;
}

.team li {
    font-size: 24px;
    margin-bottom: 5px;
    color: var(--color-light-gray);
}

footer {
    position: fixed; 
    left: 0;
    bottom: 0; 
    width: 100%; 
    background-color: var(--color-dark-gray2); 
    color: var(--color-light-gray2); 
    padding: 10px 0; 
    text-align: center; 
    font-size: 17px;
}

footer p {
    margin: 0; 
}

.colored-green {
    color: var(--color-light-green);
}

.logo {
    position: absolute;
    left: calc(100% - 120px); 
    top: 0px;

/* Essas 2 linhas de código não fazem nada aqui porque na classe ".logo img" você pode definir diretamente a largura e a altura para 100px
    width: 100px;
    height: 100px; */
}

.logo img {
    width: 100%; /* Altere para 100px */
    height: 100%; /* Altere para 100px */
}

.navbar a {
    float: left;
    display: block;
    color: var(--color-light-gray);
    text-align: center;
    padding: 36px 36px;
    text-decoration: none;
    font-size: 24px;
}

.navbar a:hover {
    color: var(--color-light-green);
    overflow: hidden;
}

/* Responsividade continua igual aqui */
```

---

### `estilo_sobre.css`
```CSS
:root {
    --color-light-green: #64AC72; /* Verde claro */
    --color-light-gray: #BCBCBC; /* Cinza claro */
    --color-light-gray2: #A4A4A4; /* Outro cinza claro */
    --color-gray: #9B9FA5; /* Cinza */
    --color-dark-gray: #333; /*  Cinza escuro */
    --color-dark-gray2: #2E2E2E /* Outro cinza escuro */
    --color-white: #f9f9f9; /* Cor quase branco */
    --color-white2: #E0E0E0; /* Outro quase branco */
} 
 
* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

body {
    font-family: Arial, Helvetica, sans-serif;
    background: url('images/background.png') no-repeat center center / cover;
    background-attachment: fixed;
    min-height: 100vh;
    font-size: 24px;
    color: var(--color-dark-gray);
    background-color: var(--color-white);
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    line-height: 1.6;
    margin: 20px;
}

.container {
    padding: 36px;
    color: var(--color-gray);
    position: absolute;
    top: 250px;
    left: 20px;
    width: 1200px;
    height: auto;
}

h1 {
    font-size: 24px;
    margin-bottom: 10px;
    color: var(--color-white2); 
    font-weight: 300; 
}

.description {
    font-size: 24px;
    margin-bottom: 20px;
    color: var(--color-light-gray); 
}

.centered-image {
    display: block;
    max-width: 100%;
    height: auto;
    margin: 0 auto;
    transform: translateX(-10px); 
}

.green-text {
    color: var(--color-light-green);
}

footer {
    position: fixed;
    left: 0;
    bottom: 0; 
    width: 100%; 
    background-color: var(--color-dark-gray2); 
    color: var(--color-light-gray2); 
    padding: 10px 0; 
    text-align: center; 
    font-size: 17px; 
}

footer p {
    margin: 0; 
}

.colored-green {
    color: var(--color-light-green);
}

.logo {
    position: absolute;
    left: calc(100% - 120px); 
    top: 0px;

/* Essas 2 linhas de código não fazem nada aqui porque na classe ".logo img" você pode definir diretamente a largura e a altura para 100px 
    width: 100px;
    height: 100px; */
    
}

.logo img {
    width: 100%; /* Altere para 100px */
    height: 100%; /* Altere para 100px */
}

.navbar a {
    float: left;
    display: block;
    color: var(--color-light-gray);
    text-align: center;
    padding: 36px 36px;
    text-decoration: none;
    font-size: 24px;
}

.navbar a:hover {
    color: var(--color-light-green);
    overflow: hidden;
}

/* Responsividade continua igual aqui */

```

<div align="center">
    <h3>🚀Mudanças</h3>
</div>

<br>

 - Guardei os `hexadecimais` das cores do seu site e coloquei em variáveis
 - No lugar dos hexadecimais botei `var(--nome-da-variável);`
